"""empty message

Revision ID: 554b4f515f0a
Revises: ce3c569a5cc0
Create Date: 2025-04-30 13:57:21.488323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '554b4f515f0a'
down_revision = 'ce3c569a5cc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fav_count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.drop_column('fav_count')

    # ### end Alembic commands ###
